### ISSUE TITLE
How could I get the dataset

### ISSUE THREAD

**Issue by TianyunYoung** [OpenCausaLab/MORE#1]
Hi~ This is a great work and I want to follow. 

How could I get the dataset mentioned in the Readme file? Thank you very much.

**Comment by chenmeiqii** [comment]
> Hi~ This is a great work and I want to follow.
> 
> How could I get the dataset mentioned in the Readme file? Thank you very much.

Hi, Thanks for your interest! You can access our dataset at the following link: [MORE Data](https://github.com/OpenCausaLab/MORE/tree/main/dataset)
